model:
  samblip_pretrained_path: "/data/xcg/lavis_data/output/BLIP2/best_results/checkpoint_2.pth"
  mlp_pretrained_path: "/home/xcg/medical-research/Project23us/checkpoints/mlp_untrained_0.pth"
  # mlp_pretrained_path: "/home/xcg/medical-research/Project23us/checkpoints/mlp_checkpoint_1.pth"

run:

  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-4
  min_lr: 1e-5
  warmup_lr: 1e-6
  lr_layer_decay: 1
  beta2: 0.999

  weight_decay: 0.05
  max_epoch: 4
  batch_size_train: 4
  batch_size_eval: 4
  num_workers: 1
  warmup_steps: 2000
  seed: 42
  # output_dir: "/mnt/sdd/xcg_data/lavis_data/output/BLIP2/Final/BLIP2&SAM_LONG_coco&roco&medi_onlysam"
  output_dir: "/data/xcg/lavis_data/output/BLIP2/Final/BLIP2&SAM_CLIP_coco&SAM_coco"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  # lyz modifies cuda
  # no distribution
  device: "cuda:0"
  world_size: 1
  dist_url: "env://"
  distributed: False


dataset:
  batch_size: 4
  limitation: 8
  shuffle: False
  # dataset_base: "/data2/xcg_data/lavis_data/2023us/features"
  dataset_base: "/data2/xcg_data/lavis_data/Breast_images/features"
  # csv_path: "/data/xcg/lavis_data/coco-2023us/excels/translated.csv"
  csv_path: ""




